### ISSUE TITLE
Generator fails with YAML dumper exception

### ISSUE THREAD

**Issue by demius** [event-catalog/generator-asyncapi#67]
### I tried this:

I have tried to use the generator with the simplest AsyncAPI specification I can find, as well as the examples included in this repository.

I've stripped it down to the simplest specification I could find:

```
asyncapi: 3.0.0
info:
  title: Hello world application
  version: '0.1.0'
channels:
  hello:
    address: 'hello'
    messages:
      sayHelloMessage:
        payload:
          type: string
          pattern: '^hello .+$'
operations:
  receiveHello:
    action: 'receive'
    channel:
      $ref: '#/channels/hello'
```

### This happened:

The generate command offers me the following stacktrace, regardless of what I do:

```
Processing domain: Content (v0.0.1)
 - Domain (v0.0.1) created
Error loading plugin: YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (/Users/alexisv/Documents/Repos/spark-bonfire/bonfire-event-catalog/bonfire/node_modules/gray-matter/node_modules/js-yaml/lib/js-yaml/dumper.js:779:13)
    at writeBlockMapping (/Users/alexisv/Documents/Repos/spark-bonfire/bonfire-event-catalog/bonfire/node_modules/gray-matter/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
    at writeNode (/Users/alexisv/Documents/Repos/spark-bonfire/bonfire-event-catalog/bonfire/node_modules/gray-matter/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
    at writeBlockSequence (/Users/alexisv/Documents/Repos/spark-bonfire/bonfire-event-catalog/bonfire/node_modules/gray-matter/node_modules/js-yaml/lib/js-yaml/dumper.js:542:9)
    at writeNode (/Users/alexisv/Documents/Repos/spark-bonfire/bonfire-event-catalog/bonfire/node_modules/gray-matter/node_modules/js-yaml/lib/js-yaml/dumper.js:763:9)
    at writeBlockMapping (/Users/alexisv/Documents/Repos/spark-bonfire/bonfire-event-catalog/bonfire/node_modules/gray-matter/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
    at writeNode (/Users/alexisv/Documents/Repos/spark-bonfire/bonfire-event-catalog/bonfire/node_modules/gray-matter/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
    at dump (/Users/alexisv/Documents/Repos/spark-bonfire/bonfire-event-catalog/bonfire/node_modules/gray-matter/node_modules/js-yaml/lib/js-yaml/dumper.js:840:7)
    at Object.safeDump (/Users/alexisv/Documents/Repos/spark-bonfire/bonfire-event-catalog/bonfire/node_modules/gray-matter/node_modules/js-yaml/lib/js-yaml/dumper.js:846:10)
    at module.exports (/Users/alexisv/Documents/Repos/spark-bonfire/bonfire-event-catalog/bonfire/node_modules/gray-matter/lib/stringify.js:38:25) {
  reason: 'unacceptable kind of an object to dump [object Undefined]',
  mark: undefined
}
```

### Is there a workaround?

No known workaround

### Anything else?

I am using version 2.1.1 of the Async API generator.
I have attempted the same with version 1.0.5 and that does seem to work.

### EventCatalog Version

latest

### Node.js Version

20.15.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by demius** [comment]
This seems to be related to https://github.com/event-catalog/generator-asyncapi/issues/27 as I'm seeing the same invalid spec generated by the service.

**Comment by demius** [comment]
I think that there was a problem with my specification and in the end, the issue resolved itself after some tinkering.
